service: aws-todo-app
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:REGION}
  environment:
    ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    REGION: ${env:REGION}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}

functions:
  api:
    handler: dist/index.handler
    events:
      - httpApi: '*'

plugins:
   - serverless-offline
   - serverless-dotenv-plugin

package:
  patterns:
    - '!node_modules/**'
    - '!app/**'
    - '!Dockerfile'
    - '!package**'
    - '!**.ts'
    - '!README.md'
    - '!tsconfig.json'
    - 'dist'